### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by SetOfAllSets** [nikgapps/build#158]
I am unable to build (please respond quickly, my phone's gapps don't work after a software update).
Upon running `python3 config_control.py --androidVersion 14` I get the error
```Checking if there is any existing workflow in progress
Total Open Workflows: 0
Finding the open pull requests
'NoneType' object has no attribute 'json'
'NoneType' object has no attribute 'json'
Total Open Pull Requests: 0
/home/set/nikgapps/config already exists, deleting for a fresh clone!
git clone -b main --depth=1 git@github.com:nikgapps/config.git
Exception caught while cloning the repo: Cmd('git') failed due to: exit code(128)
  cmdline: git clone -v --branch=main --depth=1 git@github.com:nikgapps/config.git /home/set/nikgapps/config
  stderr: 'Cloning into '/home/set/nikgapps/config'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Failed to setup config directory
```
It is important to note I had to change requirements.txt to use a newer version of pyaml so it would install without error. I am building in a venv.

**Comment by SetOfAllSets** [comment]
Upon editing `NikGapps/Config/ConfigDirectoy.py` to use my fork with my file I now get the output
```
Checking if there is any existing workflow in progress
Total Open Workflows: 0
Finding the open pull requests
'NoneType' object has no attribute 'json'
'NoneType' object has no attribute 'json'
Total Open Pull Requests: 0
/home/set/nikgapps/config already exists, deleting for a fresh clone!
git clone -b main --depth=1 https://github.com/SetOfAllSets/config.git
---------------------------------------
--- Time taken to clone -b main https://github.com/SetOfAllSets/config.git ---
--- 1.375236988067627 seconds --- 
--- 0 minutes 1 seconds --- 
---------------------------------------
---------------------------------------
--- Total time taken by the program to build custom builds ---
--- 2.254923105239868 seconds --- 
--- 0 minutes 2 seconds --- 
---------------------------------------
```
and no build is created

**Comment by SetOfAllSets** [comment]
Somehow, when using run.py, it creates all zip files regardless of args, and all of them are empty! Zero bytes! Using config_ondemand.py with the right args finally built what I was asking it to... but it didn't fix my OS issue (unrelated to this git issue I suppose). This build system is horrifically bad.

**Comment by SetOfAllSets** [comment]
Cloning git repos also rarely works since it tries to login as the `git` user (seriously??) to all repos (and uses the nikgapps official repo and can't be configured to use forks). I had to manually replace git@github.com:nikgapps/* with https://github.com/SetOfAllSets/*.

**Comment by SetOfAllSets** [comment]
Oh! Oh my god! The zip file it made had 0 packages! It was sideloadable, it just didn't do anything! How nice!
EDIT: sorry I'm just upset I factory reset to try like that since it wasn't fixing my system otherwise.

**Comment by nikhilmenghani** [comment]
@SetOfAllSets you are looking at the wrong repository.

The one that's actively being maintained is 'project' not 'build'

And the reason why we're using git instead of https is because the same program also updates the apk automatically and cannot authenticate with https. It's much easier with git@repo.....

**Comment by nikhilmenghani** [comment]
@SetOfAllSets there is a self build part on 'project' repo which you can follow to build. Besides, as far as the cloning of repo goes, your system needs to have ssh key setup.

**Comment by SetOfAllSets** [comment]
> @SetOfAllSets you are looking at the wrong repository.
> 
> The one that's actively being maintained is 'project' not 'build'
> 
> And the reason why we're using git instead of https is because the same program also updates the apk automatically and cannot authenticate with https. It's much easier with git@repo.....

Ah! I must wasn't able to find that one, thank you.
I can be the user git@github.com? That doesn't sound right. Maybe I'm misunderstanding. Closing the issue anyway since this repo is unmaintained, I'd recommend marking it as such in the settings to prevent others making my mistake. Thanks!

**Comment by SetOfAllSets** [comment]
forgot to close on prev comment
