### ISSUE TITLE
Error 2

### ISSUE THREAD

**Issue by dkoek** [nikgapps/build#22]
When I try to install nikgapps-basic-arm64-11-20210607 I get an error 2.
I did made a clean install on Xiami Redmi Note 7 with the official Lineage 18.1 (Android 11).

Second I wiped data again and the message persist.

What am I doing wrong ?

**Comment by nikhilmenghani** [comment]
@dkoek can you send me the installation logs generated in /sdcard/NikGapps folder?

**Comment by nikhilmenghani** [comment]
@dkoek try the latest stable release (June 27), should be fixed now. Reopen the issue if the problem still persists.
