### ISSUE TITLE
Google markup as an addon

### ISSUE THREAD

**Issue by vnghia** [nikgapps/build#62]
Thank you for a wonderful gapps package. I found Google Markup particularly useful and I wonder if you could make it as a standalone addon ?

Thank you very much once again !

**Comment by nikgapps** [comment]
@vnghia it's already there. check https://sourceforge.net/projects/nikgapps/files/Releases/Addons-Q/21-Apr-2022/NikGapps-Addon-10-MarkupGoogle-20220421-signed.zip/download

**Comment by vnghia** [comment]
@nikgapps it doesn't have a version of android 12.1 ?

**Comment by nikgapps** [comment]
@vnghia https://sourceforge.net/projects/nikgapps/files/Releases/Addons-SL/21-Apr-2022/NikGapps-Addon-12.1-MarkupGoogle-20220421-signed.zip/download

**Comment by vnghia** [comment]
Thank you !
